### ISSUE TITLE
Regex literals issue

### ISSUE THREAD

**Issue by soulseekah** [tikitu/jsmin#1]
``` python
>>> jsmin.jsmin('function foo(){/https?:\/\//.test(a)}')
'function foo(){/https?:\\/\\'
```

...breakage. Still haven't figured out what it's caused by.

**Comment by soulseekah** [comment]
Okay, isolated to:

``` python
>>> jsmin.jsmin('{/\//.test("a")}')
'{/\\'
```

Works with extra brackets:

``` python
>>> jsmin.jsmin('{(/\//.test("a"))}')
'{(/\\//.test("a"))}'
```

Extra test added:

``` diff
diff --git a/jsmin/test.py b/jsmin/test.py
index d05ce4b..3314609 100644
--- a/jsmin/test.py
+++ b/jsmin/test.py
@@ -323,6 +323,11 @@ var  foo    =  "hey";
         original = '/a (a)/.test("a")'
         self.assertMinified(original, original)

+    def test_brackets_around_slashed_regex(self):
+        original = 'function a() { /\//.test("a") }'
+        expected = 'function a(){/\//.test("a")}/'
+        self.assertMinified(original, expected)
+
     def test_angular_1(self):
         original = '''var /** holds major version number for IE or NaN for real browsers */
                       msie,
```

Getting: `test_brackets_around_slashed_regex (jsmin.test.JsTests) ... FAIL`

**Comment by soulseekah** [comment]
So more research and thoughts as I debugged this:

`doing_single_comment = True` is being triggered as the engine thinks that `\//` is a comment, thus simply removing everything. A simple test with this regular expression `/\/a/` yields positive results as there's no longer a `//` pair.

But shouldn't `in_re` be `True`, why is this skipped? And how the heck do the curly braces contribute to the issue? Without curly braces `in_re` is always `True` during the `//` pair, so apparently `in_re` is not being set across the `{/` boundary.

Compare (added `print(in_re)` to line 203):

``` python
>>> print(jsmin.jsmin('{/\//.test')
False
False
"{/\"

>>> jsmin.jsmin('/\//.test')
True
True
"/\//.test"
```

So what's going on? Since `in_re` is set to `False` only in the beginning, it must mean that `{/` doesn't trigger the `in_re = True` clause somewhere. And why the heck does `[/\//.test]` work well if `[` seems to be the same class of characters as the `{` (i.e. a `starter`). Trusty `trace` module to the rescue and a trace diff later it seems that up to the first `in_re` check everything is identical and the only place `in_re` is being modified is at:

`__init__.py(217):                     in_re = previous_non_space in '(,=:[?!&|;' or self.is_return` (note line number may not match due to the debug code I injected here and there)

And, of course, in the failing case that expression returns a `False`, boo :(

Ah, and here we catch the difference between `[` and `{` where the latter is not in the list. Adding it to the list fixes things, but does it break others?...

```
Ran 49 tests in 0.007s

OK
```

Any ideas?

Fix is:

``` diff
diff --git a/jsmin/__init__.py b/jsmin/__init__.py
index 93c8176..11f8e50 100644
--- a/jsmin/__init__.py
+++ b/jsmin/__init__.py
@@ -213,7 +213,7 @@ class JavascriptMinify(object):
                     next1 = next2
                     next2 = read(1)
                 else:
-                    in_re = previous_non_space in '(,=:[?!&|;' or self.is_return  # literal regular expression
+                    in_re = previous_non_space in '{(,=:[?!&|;' or self.is_return  # literal regular expression
                     write('/')
             else:
                 if do_space:
```

**Comment by tikitu** [comment]
Thanks heaps for this effort! The regex-literal code is the source of almost every bug I've seen in the last year here, so it doesn't surprise me too much that you found another place it breaks. I will take a good look at your PR and hopefully get a new release out, but it will take me a while: I'm travelling at the moment and don't have much time spare. Hope to have it looked at by the end of coming weekend.

**Comment by soulseekah** [comment]
Thanks. No rush, I've tested it with the broken script (https://cdn.firebase.com/js/client/2.2.9/firebase.js it's already minified, but you can search for `{/https?:\//` this is where the code breaks), Angular, jQuery and a couple of other libraries (thinking about how to do this testing as part of unit-tests as you suggested on bitbucket). My patch will be deployed on a minifying CDN we're running in beta in the coming week or two to see if anyone reports any issues with their scripts.
