### ISSUE TITLE
re delimiters // and if make broken js.

### ISSUE THREAD

**Issue by kilgoretrout1985** [tikitu/jsmin#12]
This code from Django 1.8.5 admin (yes, no semicolon, but still valid js if I'm not mistaken).

```
var re = /\d{4}/
if (re.test(year.toString()) && month >= 1 && month <= 12) {
    DateTimeShortcuts.calendars[num].drawDate(month, year, selected);
}
```

becomes

`var re=/\d{4}/if(re.test(year.toString())&&month>=1&&month<=12) ...`

And it ends up with Firefox error - SyntaxError: invalid regular expression flag f. 

Tried jsmin==2.1.5

**Comment by tikitu** [comment]
Thanks for the report; I'm preparing a release which differs by just one single character, which fixes this issue.

Also: nice nick.
