### ISSUE TITLE
Double slash in URL in HTML is treated as JS comment.

### ISSUE THREAD

**Issue by mknaf** [tikitu/jsmin#18]
The following code isn't being minified correctly. This:

```
$("#some_element").html(`
<div class="menu">
    <!-- make sure to use right iso 3166-2 code.
    See also http://example.com/some-url.html -->
    <div class="item">item 1</div>
    <!--
    <div class="item">item 2</div>
    -->
    <div class="item">item 3</div>
</div>
`);
```

becomes this:

```
$("#some_element").html(`<div class="menu"><!--
make sure to use right iso 3166-2 code.See also http:<div class="item">item 1</div><!--<div class="item">item 2</div>--><div class="item">item 3</div></div>`);
```

Apparently, the double slash in the URI inside the HTML comment is being treated as an opening JS comment tag. Thus, this line is dropped by minification together with the closing HTML comment tag. 

This in turn creates an opening HTML comment tag with no (intentionally) related closing tag, in this case putting the first item inside of a HTML comment instead of into the menu. This can get arbitrarily worse depending on the HTML comments in the document - if there is no other comment after this, the whole rest of the document will disappear inside of a comment.

This happens with `jsmin 2.2.1` on Python 2 as well as Python 3.

**Comment by tikitu** [comment]
This is a flow-on consequence of `jsmin` not being able to handle backquote-strings (template literals). As with #19, this is "broken by design" I'm afraid. I don't have time to make `jsmin` ES6-compatible, so unless someone else steps up to maintain it it will slowly (or quickly) become irrelevant.
