### ISSUE TITLE
Template literals not working correctly

### ISSUE THREAD

**Issue by mknaf** [tikitu/jsmin#19]
[Javascript Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) aren't treated correctly.

Input:

```
var template_strings = [
    `What is 1+1? It's 2.`
];

```

Output:

```
var template_strings=[`What is 1+1?It'
```

**Comment by tikitu** [comment]
This is "broken by design" I'm afraid: template literals are an ES6 feature, and I don't have the time to make `jsmin` ES6-compatible. This is [noted in the README](https://github.com/tikitu/jsmin#usage).
