### ISSUE TITLE
Prevent spaces being removed from templates (handlebars, underscore) and multiline strings

### ISSUE THREAD

**Issue by AlexAnzolaJ** [tikitu/jsmin#24]
In following situation, using an underscore template, the minimizing process removes spaces that are necessary for the layout:

```
let _row = `
    <tr>
        <th>Income <%= current_year %> USD</th>
        <th>Tax Rate %</th>
    </tr>
`
```

The code gets shortened to:
```
let _row=<tr><th>Income<%=current_year%>USD</th><th>Tax Rate%</th></tr>
```
Resulting in output like:
> Income2017UDS Tax Rate%

I there a way to prevent this behaviour?

**Comment by tikitu** [comment]
Looks to me like you're not using the `quote_chars` parameter, try:

    jsmin.jsmin(file_contents, quote_chars="'\"`')

to recognise the backticks as string delimiters.

However please note that this is a cheap workaround, and I haven't tried to make jsmin *really* ES6-compatible: ES6 introduced a whole heap of syntax changes (including multiline strings and the template strings which are tripping you up here), and I simply don't have time to update jsmin to match. (I'm happy to pass it over to a new maintainer if someone wants to step up.)
