### ISSUE TITLE
Should remove trailing commas to support older browsers

### ISSUE THREAD

**Issue by alanhamlett** [tikitu/jsmin#25]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

Jsmin should remove dangling commas from arrays, objects, and functions to support older browsers.

**Comment by tikitu** [comment]
If I understand the issue correctly, I don't think `jsmin` should do this: its intent is not to improve anything about the input JS (including in this case its browser-compatibility), but simply to make it smaller (without changing its meaning _at all_).

In addition, I'm not really supporting `jsmin` any more: the language has moved in directions that would be rather difficult to support without a comprehensive rewrite (which I don't have the JS-knowledge or the time for), so I think it's ok to let this tool fade gently into irrelevance.
