### ISSUE TITLE
In the README, please add a link to the documentation

### ISSUE THREAD

**Issue by martinthurn** [tikitu/jsmin#29]
What exactly does jsmin() return?  A string, or a list of strings, or a dict, or what?  
How exactly do we use the quote_chars() method?  What exactly do quote chars do?
How can we change or select the comment characters?  Hash # doesn't seem to be recognized.  
Where is the documentation?  Thank you

**Comment by tikitu** [comment]
The only documentation is the README itself. I expect this library to fade out of relevance since it is not updated for new javascript versions, so I don't intend to improve the documentation at this point.
