### ISSUE TITLE
jsmin 2.1.3: SyntaxError: unterminated regular expression literal

### ISSUE THREAD

**Issue by JaakkoTulkki** [tikitu/jsmin#6]
Hi,

when minifying https://github.com/scottjehl/Respond/blob/master/src/respond.js I get an error:

SyntaxError: unterminated regular expression literal
data:,/\* EXPRESSION EVALUATED USING THE FIREBUG COMMAND LINE: _/%0A(function(w)%7B%22use%20strict%22%3B%20var%20respond%3D%7B%7D%3Bw.respond%3Drespond%3B%20respond.update%3Dfunction()%7B%7D%3B%20var%20requestQueue%3D%5B%5D%2CxmlHttp%3D(function()%7Bvar%20xmlhttpmethod%3Dfalse%3Btry%7Bxmlhttpmethod%3Dnew%20w.XMLHttpRequest()%3B%7D%0Acatch(e)%7Bxmlhttpmethod%3Dnew%20w.ActiveXObject(%22Microsoft.XMLHTTP%22)%3B%7D%0Areturn%20function()%7Breturn%20xmlhttpmethod%3B%7D%3B%7D)()%2C%20ajax%3Dfunction(url%2Ccallback)%7Bvar%20req%3DxmlHttp()%3Bif(!req)%7Breturn%3B%7D%0Areq.open(%22GET%22%2Curl%2Ctrue)%3Breq.onreadystatechange%3Dfunction()%7Bif(req.readyState!%3D%3D4%7C%7Creq.status!%3D%3D200%26%26req.status!%3D%3D304)%7Breturn%3B%7D%0Acallback(req.responseText)%3B%7D%3Bif(req.readyState%3D%3D%3D4)%7Breturn%3B%7D%0Areq.send(null)%3B%7D%2CisUnsupportedMediaQuery%3Dfunction(query)%7Breturn%20query.replace(respond.regex.minmaxwh%2C'').match(respond.regex.other)%3B%7D%3B%20respond.ajax%3Dajax%3Brespond.queue%3DrequestQueue%3Brespond.unsupportedmq%3DisUnsupportedMediaQuery%3Brespond.regex%3D%7Bmedia%3A%2F%40media%5B%5E%5C%7B%5D%2B%5C%7B(%5B%5E%5C%7B%5C%7D%5D_%5C%7B%5B%5E%5C%7D%5C%7B%5D_%5C%7D)%2B%2Fgi%2Ckeyframes%3A%2F%40(%3F%3A%5C-(%3F%3Ao%7Cmoz%7Cwebkit)%5C-)%3Fkeyframes%5B%5E%5C%7B%5D%2B%5C%7B(%3F%3A%5B%5E%5C%7B%5C%7D%5D_%5C%7B%5B%5E%5C%7D%5C%7B%5D_%5C%7D)%2B%5B%5E%5C%7D%5D_%5C%7D%2Fgi%2Ccomments%3A%2F%5C%2F%5C_%5B%5E_%5D_%5C_%2B(%5B%5E%2F%5D%5B%5E_%5D_%5C_%2B)_%5C%0Aurls%3A%2F(url%5C()%5B'%22%5D%3F(%5B%5E%5C%2F%5C)'%22%5D%5B%5E%3A%5C)'%22%5D%2B)%5B'%22%5D%3F(%5C))%2Fg%2CfindStyles%3A%2F%40media%20_(%5B%5E%5C%7B%5D%2B)%5C%7B(%5B%5CS%5Cs%5D%2B%3F)%24%2F%2Conly%3A%2F(only%5Cs%2B)%3F(%5Ba-zA-Z%5D%2B)%5Cs%3F%2F%2Cminw%3A%2F%5C(%5Cs_min%5C-width%5Cs_%3A%5Cs_(%5Cs_%5B0-9%5C.%5D%2B)(px%7Cem)%5Cs_%5C)%2F%2Cmaxw%3A%2F%5C(%5Cs_max%5C-width%5Cs_%3A%5Cs_(%5Cs_%5B0-9%5C.%5D%2B)(px%7Cem)%5Cs_%5C)%2F%2Cminmaxwh%3A%2F%5C(%5Cs_m(in%7Cax)%5C-(height%7Cwidth)%5Cs_%3A%5Cs_(%5Cs_%5B0-9%5C.%5D%2B)(px%7Cem)%5Cs_%5C)%2Fgi%2Cother%3A%2F%5C(%5B%5E%5C)%5D_%5C)%2Fg%7D%3B%20respond.mediaQueriesSupported%3Dw.matchMedia%26%26w.matchMedia(%22only%20all%22)!%3D%3Dnull%26%26w.matchMedia(%22only%20all%22).matches%3B%20if(respond.mediaQueriesSupported)%7Breturn%3B%7D%20%0Avar%20doc%3Dw.document%2CdocElem%3Ddoc.documentElement%2Cmediastyles%3D%5B%5D%2Crules%3D%5B%5D%2CappendedEls%3D%5B%5D%2CparsedSheets%3D%7B%7D%2CresizeThrottle%3D30%2Chead%3Ddoc.getElementsByTagName(%22head%22)%5B0%5D%7C%7CdocElem%2Cbase%3Ddoc.getElementsByTagName(%22base%22)%5B0%5D%2Clinks%3Dhead.getElementsByTagName(%22link%22)%2ClastCall%2CresizeDefer%2C%20eminpx%2C%20getEmValue%3Dfunction()%7Bvar%20ret%2Cdiv%3Ddoc.createElement('div')%2Cbody%3Ddoc.body%2CoriginalHTMLFontSize%3DdocElem.style.fontSize%2CoriginalBodyFontSize%3Dbody%26%26body.style.fontSize%2CfakeUsed%3Dfalse%3Bdiv.style.cssText%3D%22position%3Aabsolute%3Bfont-size%3A1em%3Bwidth%3A1em%22%3Bif(!body)%7Bbody%3DfakeUsed%3Ddoc.createElement(%22body%22)%3Bbody.style.background%3D%22none%22%3B%7D%0A%20%0AdocElem.style.fontSize%3D%22100%25%22%3Bbody.style.fontSize%3D%22100%25%22%3Bbody.appendChild(div)%3Bif(fakeUsed)%7BdocElem.insertBefore(body%2CdocElem.firstChild)%3B%7D%0Aret%3Ddiv.offsetWidth%3Bif(fakeUsed)%7BdocElem.removeChild(body)%3B%7D%0Aelse%7Bbody.removeChild(div)%3B%7D%20%0AdocElem.style.fontSize%3DoriginalHTMLFontSize%3Bif(originalBodyFontSize)%7Bbody.style.fontSize%3DoriginalBodyFontSize%3B%7D%20%0Aret%3Deminpx%3DparseFloat(ret)%3Breturn%20ret%3B%7D%2C%20applyMedia%3Dfunction(fromResize)%7Bvar%20name%3D%22clientWidth%22%2CdocElemProp%3DdocElem%5Bname%5D%2CcurrWidth%3Ddoc.compatMode%3D%3D%3D%22CSS1Compat%22%26%26docElemProp%7C%7Cdoc.body%5Bname%5D%7C%7CdocElemProp%2CstyleBlocks%3D%7B%7D%2ClastLink%3Dlinks%5Blinks.length-1%5D%2Cnow%3D(new%20Date()).getTime()%3B%20if(fromResize%26%26lastCall%26%26now-lastCall%3CresizeThrottle)%7Bw.clearTimeout(resizeDefer)%3BresizeDefer%3Dw.setTimeout(applyMedia%2CresizeThrottle)%3Breturn%3B%7D%0Aelse%7BlastCall%3Dnow%3B%7D%0Afor(var%20i%20in%20mediastyles)%7Bif(mediastyles.hasOwnProperty(i))%7Bvar%20thisstyle%3Dmediastyles%5Bi%5D%2Cmin%3Dthisstyle.minw%2Cmax%3Dthisstyle.maxw%2Cminnull%3Dmin%3D%3D%3Dnull%2Cmaxnull%3Dmax%3D%3D%3Dnull%2Cem%3D%22em%22%3Bif(!!min)%7Bmin%3DparseFloat(min)_(min.indexOf(em)%3E-1%3F(eminpx%7C%7CgetEmValue())%3A1)%3B%7D%0Aif(!!max)%7Bmax%3DparseFloat(max)_(max.indexOf(em)%3E-1%3F(eminpx%7C%7CgetEmValue())%3A1)%3B%7D%20%0Aif(!thisstyle.hasquery%7C%7C(!minnull%7C%7C!maxnull)%26%26(minnull%7C%7CcurrWidth%3E%3Dmin)%26%26(maxnull%7C%7CcurrWidth%3C%3Dmax))%7Bif(!styleBlocks%5Bthisstyle.media%5D)%7BstyleBlocks%5Bthisstyle.media%5D%3D%5B%5D%3B%7D%0AstyleBlocks%5Bthisstyle.media%5D.push(rules%5Bthisstyle.rules%5D)%3B%7D%7D%7D%0Afor(var%20j%20in%20appendedEls)%7Bif(appendedEls.hasOwnProperty(j))%7Bif(appendedEls%5Bj%5D%26%26appendedEls%5Bj%5D.parentNode%3D%3D%3Dhead)%7Bhead.removeChild(appendedEls%5Bj%5D)%3B%7D%7D%7D%0AappendedEls.length%3D0%3B%20for(var%20k%20in%20styleBlocks)%7Bif(styleBlocks.hasOwnProperty(k))%7Bvar%20ss%3Ddoc.createElement(%22style%22)%2Ccss%3DstyleBlocks%5Bk%5D.join(%22%5Cn%22)%3Bss.type%3D%22text%2Fcss%22%3Bss.media%3Dk%3Bhead.insertBefore(ss%2ClastLink.nextSibling)%3Bif(ss.styleSheet)%7Bss.styleSheet.cssText%3Dcss%3B%7D%0Aelse%7Bss.appendChild(doc.createTextNode(css))%3B%7D%20%0AappendedEls.push(ss)%3B%7D%7D%7D%2C%20translate%3Dfunction(styles%2Chref%2Cmedia)%7Bvar%20qs%3Dstyles.replace(respond.regex.comments%2C'').replace(respond.regex.keyframes%2C'').match(respond.regex.media)%2Cql%3Dqs%26%26qs.length%7C%7C0%3B%20href%3Dhref.substring(0%2Chref.lastIndexOf(%22%2F%22))%3Bvar%20repUrls%3Dfunction(css)%7Breturn%20css.replace(respond.regex.urls%2C%22%241%22%2Bhref%2B%22%242%243%22)%3B%7D%2CuseMedia%3D!ql%26%26media%3B%20if(href.length)%7Bhref%2B%3D%22%2F%22%3B%7D%0A%0A%0Aif(useMedia)%7Bql%3D1%3B%7D%0Afor(var%20i%3D0%3Bi%3Cql%3Bi%2B%2B)%7Bvar%20fullq%2Cthisq%2Ceachq%2Ceql%3B%20if(useMedia)%7Bfullq%3Dmedia%3Brules.push(repUrls(styles))%3B%7D%20%0Aelse%7Bfullq%3Dqs%5Bi%5D.match(respond.regex.findStyles)%26%26RegExp.%241%3Brules.push(RegExp.%242%26%26repUrls(RegExp.%242))%3B%7D%0Aeachq%3Dfullq.split(%22%2C%22)%3Beql%3Deachq.length%3Bfor(var%20j%3D0%3Bj%3Ceql%3Bj%2B%2B)%7Bthisq%3Deachq%5Bj%5D%3Bif(isUnsupportedMediaQuery(thisq))%7Bcontinue%3B%7D%0Amediastyles.push(%7Bmedia%3Athisq.split(%22(%22)%5B0%5D.match(respond.regex.only)%26%26RegExp.%242%7C%7C%22all%22%2Crules%3Arules.length-1%2Chasquery%3Athisq.indexOf(%22(%22)%3E-1%2Cminw%3Athisq.match(respond.regex.minw)%26%26parseFloat(RegExp.%241)%2B(RegExp.%242%7C%7C%22%22)%2Cmaxw%3Athisq.match(respond.regex.maxw)%26%26parseFloat(RegExp.%241)%2B(RegExp.%242%7C%7C%22%22)%7D)%3B%7D%7D%0AapplyMedia()%3B%7D%2C%20makeRequests%3Dfunction()%7Bif(requestQueue.length)%7Bvar%20thisRequest%3DrequestQueue.shift()%3Bajax(thisRequest.href%2Cfunction(styles)%7Btranslate(styles%2CthisRequest.href%2CthisRequest.media)%3BparsedSheets%5BthisRequest.href%5D%3Dtrue%3B%0A%20w.setTimeout(function()%7BmakeRequests()%3B%7D%2C0)%3B%7D)%3B%7D%7D%2C%20ripCSS%3Dfunction()%7Bfor(var%20i%3D0%3Bi%3Clinks.length%3Bi%2B%2B)%7Bvar%20sheet%3Dlinks%5Bi%5D%2Chref%3Dsheet.href%2Cmedia%3Dsheet.media%2CisCSS%3Dsheet.rel%26%26sheet.rel.toLowerCase()%3D%3D%3D%22stylesheet%22%3B%20if(!!href%26%26isCSS%26%26!parsedSheets%5Bhref%5D)%7B%20if(sheet.styleSheet%26%26sheet.styleSheet.rawCssText)%7Btranslate(sheet.styleSheet.rawCssText%2Chref%2Cmedia)%3BparsedSheets%5Bhref%5D%3Dtrue%3B%7Delse%7Bif((!%2F%5E(%5Ba-zA-Z%3A%5D_%5C%2F%5C%2F)%2F.test(href)%26%26!base)%7C%7Chref.replace(RegExp.%241%2C%22%22).split(%22%2F%22)%5B0%5D%3D%3D%3Dw.location.host)%7B%0A%20if(href.substring(0%2C2)%3D%3D%3D%22%2F%2F%22)%7Bhref%3Dw.location.protocol%2Bhref%3B%7D%0ArequestQueue.push(%7Bhref%3Ahref%2Cmedia%3Amedia%7D)%3B%7D%7D%7D%7D%0AmakeRequests()%3B%7D%3B%20ripCSS()%3B%20respond.update%3DripCSS%3B%20respond.getEmValue%3DgetEmValue%3B%20function%20callMedia()%7BapplyMedia(true)%3B%7D%0Aif(w.addEventListener)%7Bw.addEventListener(%22resize%22%2CcallMedia%2Cfalse)%3B%7D%0Aelse%20if(w.attachEvent)%7Bw.attachEvent(%22onresize%22%2CcallMedia)%3B%7D%7D)(this)%3B
Line 7

**Comment by tikitu** [comment]
Thanks for the bug report. If it's possible for you to bake it down to a smaller example it would be really helpful. See tests like this one for inspiration: https://github.com/tikitu/jsmin/blob/master/jsmin/test.py#L396

I won't have time to work on it before the weekend I'm afraid.

**Comment by tikitu** [comment]
The biggest problem with the regex literal syntax is distinguishing it from comments. Turns out `respond.js` has a regex designed to match comments. Of _course_ `jsmin` doesn't quite handle this correctly :-/

**Comment by JaakkoTulkki** [comment]
Oukidou. I'm on vacation and haven't had the chance to work on this.

**Comment by tikitu** [comment]
This is the straw that breaks my patience with the regex-literal handling. I'm now trying to factor it out: hopefully this will increase the general robustness as well.
