### ISSUE TITLE
Premature end of statement

### ISSUE THREAD

**Issue by soulseekah** [tikitu/jsmin#9]
jsmin is choking on this line here https://github.com/Automattic/jetpack/blob/d00226a061198feb72750b1bd7b980c9d9311c91/_inc/spin.js#L23 closing the statement prematurely. Here's a minimal test to reproduce for now:

``` python
    def test_empty_declaration_with_comment(self):
        original = '''
            var a /* this is a comment */
            a = 1
        '''
        self.assertMinified(original, 'var a;a=1')
```

```
AssertionError: 
got: 'var a a=1'
exp: 'var a;a=1'
```

Will follow up with more thoughts, findings and maybe a patch.

**Comment by tikitu** [comment]
Hm. Legit bug, as the result is not semantically equivalent, but your test case is slightly smarter than `jsmin` is: I don't think we do any `;` insertion. I believe the expected output would be `var a\na=1`.

Thanks heaps, btw, for minimising your test cases: it makes life much easier on this end.

**Comment by soulseekah** [comment]
Yes, you're right about `var a\na=1` since:

```
var a // this is a comment
a = 1
```

Yields `var a\na=1`, which is correct.

**Comment by soulseekah** [comment]
Some more cases that fail:

So it seems that the problem lies in terminating the statement with ; but only:
1. for block comments following: variable, function, object, number, string, array (pretty much everything yes?)
2. for line comments following: string

Examples for the first line that truncate the `\r\n` breaking the JavaScript:

```
var a = 'hi' // this is a comment
console.log(1) /* this is a comment */
1 /* this is a comment */
{} /* this is a comment */
"YOLO" /* this is a comment */
"YOLO" // this is a comment
```

Running the above yields: `var a='hi'console.log(1)1 {}"YOLO""YOLO"` with not a single `\r\n` in view.

**Comment by soulseekah** [comment]
So the problem appears to be a missing `do_newline = True` inside [`doing_multi_comment`](https://github.com/tikitu/jsmin/blob/7c29ea6ffebedf21c081339e241f9a05f0cf6b3e/jsmin/__init__.py#L146), which means there's absolutely no way to get a new line after a block comment has ended unless a new line preceded the comment (i.e. the comment was on a new line all along).

``` diff
diff --git a/jsmin/__init__.py b/jsmin/__init__.py
index f4489c9..bd90e07 100644
--- a/jsmin/__init__.py
+++ b/jsmin/__init__.py
@@ -156,7 +156,7 @@ class JavascriptMinify(object):
                         next2 = read(1)
                         if not next2:
                             break
-                    if previous_before_comment and previous_before_comment in ')}]':
+                    if previous_before_comment and previous_before_comment in '\'")}]':
                         do_newline = True
                     elif previous_before_comment and previous_before_comment in space_strings:
                         write('\n')
```

But for single comments the solution above seems to work. I merely added double and single-quotes to make sure that a new line is output after a single comment when the `previous_before_comment` is not a normal expected character (`space_strings`).

Here's a test case for single comments following statements ending in a string without a terminating semi-colon:

``` python
    def test_issue_9_comments(self):
        original = '''
            var a = "hello" // this is a comment
            a += " world"
        '''
        self.assertMinified(original, 'var a="hello" \na+=" world"')
```

Not sure how to get rid of the extra space between the `\n` and the `"`.

**Comment by soulseekah** [comment]
Here's something that seems to work for multi-line comments:

``` diff
diff --git a/jsmin/__init__.py b/jsmin/__init__.py
index f4489c9..1d0077f 100644
--- a/jsmin/__init__.py
+++ b/jsmin/__init__.py
@@ -148,6 +148,8 @@ class JavascriptMinify(object):
                     doing_multi_comment = False
                     if previous_before_comment and previous_before_comment in space_strings:
                         do_space = True
+                    if previous_before_comment and previous_before_comment in '\'")}]':
+                        do_newline = True
                     next2 = read(1)
             elif doing_single_comment:
                 if next1 in '\r\n':
```

Test case that goes with both the above trial patch and the single-comment one in my previous comment:

``` diff
diff --git a/jsmin/test.py b/jsmin/test.py
index b208890..2ee1271 100644
--- a/jsmin/test.py
+++ b/jsmin/test.py
@@ -418,6 +418,20 @@ b} and not ${2 * a + "b"}.`'''
         expected = original.replace(' ', '').replace('\n', '')
         self.assertMinified(original, expected)

+    def test_issue_9_single_comments(self):
+        original = '''
+            var a = "hello" // this is a comment
+                       a += " world"
+        '''
+        self.assertMinified(original, 'var a="hello" \na+=" world"')
+
+    def test_issue_9_multi_comments(self):
+        original = '''
+            var a = "hello" /* this is a comment */
+                       a += " world"
+        '''
+        self.assertMinified(original, 'var a="hello"\na+=" world"')
+
```

All tests seem to pass but who knows... it's pretty hairy in there :)

Any thoughts welcome, I don't like that trailing space before a single-line comment is being rid of.

**Comment by tikitu** [comment]
I'm sick of "pretty hairy in there", so I did a bit of refactoring to simplify things. @soulseekah if you had time to review #11 I would be enormously grateful. And if not, you might try checking out that branch: I think it will solve this issue (and #10 which is related), and I _hope_ it will not introduce any regressions.

**Comment by tikitu** [comment]
> Any thoughts welcome, I don't like that trailing space before a single-line comment is being rid of.

Hm. You mean that it converts `a // comment\nb` into `a\nb` instead of `a \nb`? I kept that behaviour in my refactor, I thought it was a positive point rather than negative: I assume that spaces are only needed as token separators, and that newlines will always function as token separators (and sometimes as more, because of implicit semicolon insertion). This is made explicit in 16979dd9f126bf78f737cc78620dee4b65e43438: if I'm missing something I'd love to hear about it.

**Comment by tikitu** [comment]
Ah, from the comment before ("Not sure how to get rid of...") I hope you meant exactly the opposite, which is what I think I managed to do. Let's see...

**Comment by soulseekah** [comment]
The other way around, it converted to `a \nb` instead of expected `a\nb` see `test_issue_9_single_comments` above.

As for the refactor, I'll try it out on one of our production minifiers (they're still in beta, so I can do so without any repercussions) in the coming day or two and let you know. So far the cleanup looks really good.

**Comment by soulseekah** [comment]
Also, please keep in mind, regarding the `a \nb` issue - my test were written for the current master (0962da424ed8692b9c1d5fe6db1ed1f8ac4ecf6f), the refactored code might handle this differently, haven't checked yet.

**Comment by soulseekah** [comment]
Almost 24 hours in field testing, minifying a myriad of different scripts; so far so good.
